#
#   Author: Rohith
#   Date: 2015-07-20 16:46:35 +0100 (Mon, 20 Jul 2015)
#
#  vim:ts=2:sw=2:et
#
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - name: kubectl
        image: kelseyhightower/kubectl:v1.0.0
        args:
          - -p 8001
          - --insecure-skip-tls-verify=true
          - --server=https://10.101.0.1:443
      - name: config
        image: gambol99/prometheus-config
        args:
          - -s 127.0.0.1:8001
        volumeMounts:
        - name: config
          mountPath: /opt/prometheus
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        args:
          - -config.file=/opt/prometheus/prometheus.yml
          - -storage.local.path=/prometheus
          - -web.console.libraries=/etc/prometheus/console_libraries
          - -web.console.templates=/etc/prometheus/console

        volumeMounts:
        - name: config
          mountPath: /opt/prometheus
      volumes:
      - name: config
        source:
          emptyDir: {}
