#
#   Author: Rohith
#   Date: 2015-07-23 11:14:35 +0100 (Thu, 23 Jul 2015)
#
#  vim:ts=2:sw=2:et
#

global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  labels:
    monitor: 'monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    target_groups:
      - targets: ['localhost:9090']
  - job_name: 'dynamic'
    file_sd_configs:
      - names: [ '/etc/prometheus/targets.d/*.yml' ]
